version: "3.9"

services:
  devhabit.api:
    image: ${DOCKER_REGISTRY-}devhabitapi
    build:
      context: .
      dockerfile: DevHabit.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      # OTEL za Aspire / tracing
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://devhabit.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      # Keycloak URL za JWT validaciju
      - KEYCLOAK_AUTHORITY=http://keycloak:8080/realms/myrealm
      - KEYCLOAK_AUDIENCE=myapi
      - DOTNET_RUNNING_IN_CONTAINER=true
    networks:
      - app-network

  devhabit.postgres:
    image: postgres:17.2
    environment:
      POSTGRES_DB: devhabit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.containers/postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app-network

  devhabit.seq:
    image: datalust/seq:2024.3
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - ./.containers/seq_data:/data
    ports:
      - 8082:80
      - 5341:5341
    networks:
      - app-network

  devhabit.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: Keycloak
    command: start-dev
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - C:/Users/acerPC/Desktop/Milos/kursevi/Habit-Handling/practise/Frontend/keycloakify-starter/dist_keycloak/keycloak-theme-for-kc-all-other-versions.jar:/opt/keycloak/providers/keycloak-theme.jar
    ports:
      - 18080:8080
    networks:
     - app-network
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8085:80"    # javni ulaz
      #- "443:443" # za TLS, opcionalno
    volumes:
      - C:/Users/acerPC/Desktop/Milos/kursevi/Habit-Handling/practise/DevHabit/nginx.conf:/etc/nginx/nginx.conf:ro
      - C:/Users/acerPC/Desktop/Milos/kursevi/Habit-Handling/practise/react-client-app/dist:/usr/share/nginx/html:ro
    depends_on:
      - devhabit.api
      - keycloak
    networks:
      - app-network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
        - "5672:5672"     # AMQP port
        - "15672:15672"   # Web UI za dashboard
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./.containers/rabbitmq_data:/var/lib/rabbitmq

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: Jaeger
    ports:
      - 4317:4317
      - 4318:4318
      - 16686:16686

networks:
  app-network:
    driver: bridge
