// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DevHabit.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class AutomationSourceAdd : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "automation_source",
                schema: "dev_habit",
                table: "habits",
                newName: "_automation_source");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "_automation_source",
                schema: "dev_habit",
                table: "habits",
                newName: "automation_source");
        }
    }
}
